version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: "./Dockerfile"
    env_file:
      - "./.env.local"
    restart: always

  nginx:
    image: "nginx:stable-alpine"
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
